version: 0.0
Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "test-deploy-first-function-hello"
        Alias: "testAlias"
        CurrentVersion: "8"
        TargetVersion: "12"
