version: 2
jobs:
  build:
    docker:
      environment:
        AWS_CODE_DEPLOY_REGION: us-east-1
        AWS_CODE_DEPLOY_APPLICATION_NAME: "test-deploy"
        AWS_CODE_DEPLOY_DEPLOYMENT_CONFIG_NAME: test-deploy
        AWS_CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: "test-group"
        AWS_CODE_DEPLOY_SERVICE_ROLE_ARN: "arn:aws:iam::475203788952:role/code-deploy"
        #AWS_CODE_DEPLOY_EC2_TAG_FILTERS: "Key=Type,Value=www,Type=KEY_AND_VALUE".
        AWS_CODE_DEPLOY_APP_SOURCE: /home/popsovik/projects/test-ci/code-deploy/.serverless
        AWS_CODE_DEPLOY_S3_FILENAME: blabla-test.zip #####"${CIRCLE_BUILD_NUM}#${CIRCLE_SHA1:0:7}.zip"
        AWS_CODE_DEPLOY_S3_BUCKET: testd-eploy-rhjrjtyjtyukut
        AWS_CODE_DEPLOY_S3_KEY_PREFIX: /test
        AWS_CODE_DEPLOY_S3_LIMIT_BUCKET_FILES: 10
        AWS_CODE_DEPLOY_S3_SSE: true
        #AWS_CODE_DEPLOY_REVISION_DESCRIPTION: "${CIRCLE_BRANCH} (#${CIRCLE_SHA1:0:7})"..
        #AWS_CODE_DEPLOY_DEPLOYMENT_DESCRIPTION: "Deployed via CircleCI on $(date)".
        #AWS_CODE_DEPLOY_DEPLOYMENT_FILE_EXISTS_BEHAVIOR: "OVERWRITE"
      # specify the version you desire here
      - image: circleci/node:10.10.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install
      - run: sudo npm install -g serverless
      - run: sls deploy --stage CI-test --region us-east-1

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      #- run: yarn test