version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.10.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install
      - run: sudo apt-get install python-dev
      - run: sudo npm install aws-code-deploy -g
      - run: sudo npm install -g serverless
#      - run: sls deploy --stage CI-test --region us-east-1
      - run: sls package
      - run: aws-code-deploy

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      #- run: yarn test